In [37]:
import numpy as np
import pandas as pd

In [38]:
df=pd.read_csv("Bangalore_Restaurants.csv")
print(df)

           Restaurant_Name                                           Category  \
0              Burma Burma  Asian, Burmese, Bubble Tea, Salad, Tea, Desser...   
1     Windmills Craftworks  Continental, Fast Food, Kebab, Beverages, Ital...   
2           CTR Shri Sagar                                       South Indian   
3     Brahmin's Coffee Bar                                       South Indian   
4         Milano Ice Cream                     Desserts, Ice Cream, Beverages   
...                    ...                                                ...   
5104     Chopstick Kitchen                            Chinese, Momos, Seafood   
5105         Punjabi Dhaba                                       North Indian   
5106  Abhiruchi Restaurant  Biryani, Andhra, North Indian, Chinese, Hydera...   
5107      The Q Restaurant                      North Indian, Chinese, Kerala   
5108      Flavors Of India           North Indian, Chinese, Andhra, Fast Food   

      Pricing_for_2        

In [39]:
df.head()

Restaurant_Name                                           Category  \
0           Burma Burma  Asian, Burmese, Bubble Tea, Salad, Tea, Desser...   
1  Windmills Craftworks  Continental, Fast Food, Kebab, Beverages, Ital...   
2        CTR Shri Sagar                                       South Indian   
3  Brahmin's Coffee Bar                                       South Indian   
4      Milano Ice Cream                     Desserts, Ice Cream, Beverages   

   Pricing_for_2                          Locality  Dining_Rating  \
0           1500            Indiranagar, Bangalore            4.9   
1           2500   Windmills Craftworks, Bangalore            4.9   
2            150           Malleshwaram, Bangalore            4.9   
3            100           Basavanagudi, Bangalore            4.9   
4            400            Indiranagar, Bangalore            4.9   

   Dining_Review_Count  Delivery_Rating  Delivery_Rating_Count  \
0               2790.0              4.5                  838.0   
1               6543.0              4.2                  524.0   
2               4837.0              4.3                22100.0   
3               2975.0              4.4                  372.0   
4               2575.0              4.4                 1180.0   

                                             Website  \
0  https://www.zomato.com/bangalore/burma-burma-i...   
1  https://www.zomato.com/bangalore/windmills-cra...   
2  https://www.zomato.com/bangalore/ctr-shri-saga...   
3  https://www.zomato.com/bangalore/brahmins-coff...   
4  https://www.zomato.com/bangalore/milano-ice-cr...   

                                             Address   Latitude  Longitude  
0  607, Ground Floor, 12th Main, Hal 2nd Stage, I...  12.970394  77.644713  
1  78, Immaine Epip Industrial Area, Whitefield B...  12.982413  77.721979  
2   7th Cross, Margosa Road, Malleshwaram, Bangalore  12.998270  77.569455  
3       Ranga Rao Road, Near Basavanagudi, Bangalore  12.954043  77.568865  
4  460, 2nd Cross, Krishna Temple Road, Indiranag...  12.979121  77.644039

In [40]:
df.isnull().sum()

Restaurant_Name             0
Category                    0
Pricing_for_2               0
Locality                    0
Dining_Rating               8
Dining_Review_Count         8
Delivery_Rating          1412
Delivery_Rating_Count       8
Website                     0
Address                     0
Latitude                    0
Longitude                   0
dtype: int64

In [41]:
df["Dining_Rating"].unique()

array([4.9, 4.8, 4.7, 4.6, 4.5, 4.4, 4.3, nan, 4.2, 4.1, 4. , 3.9, 3.8,
       3.7, 3.6, 3.5, 3.4, 3.3])

In [42]:
df["Dining_Review_Count"].unique()

array([2.790e+03, 6.543e+03, 4.837e+03, 2.975e+03, 2.575e+03, 1.858e+03,
       1.083e+03, 1.660e+04, 1.306e+03, 1.842e+03, 4.814e+03, 8.770e+02,
       8.090e+02, 2.798e+03, 2.401e+03, 1.144e+03, 6.936e+03, 2.550e+04,
       8.760e+02, 5.950e+03, 8.938e+03, 7.881e+03, 3.228e+03, 4.340e+03,
       3.017e+03, 2.715e+03, 1.301e+03, 2.086e+03, 2.894e+03, 1.869e+03,
       8.660e+02, 2.133e+03, 2.827e+03, 5.646e+03, 4.443e+03, 8.344e+03,
       2.425e+03, 1.630e+04, 7.954e+03, 2.005e+03, 1.968e+03, 2.391e+03,
       2.284e+03, 2.331e+03, 2.458e+03, 6.045e+03, 2.497e+03, 1.384e+03,
       3.184e+03, 1.579e+03, 2.242e+03, 2.410e+03, 1.080e+04, 2.382e+03,
       1.439e+03, 2.767e+03, 3.194e+03, 2.081e+03, 6.700e+02, 1.893e+03,
       3.411e+03, 1.640e+04, 6.210e+03, 2.500e+03, 3.242e+03, 2.273e+03,
       3.872e+03, 4.993e+03, 2.956e+03, 5.850e+03, 5.185e+03, 2.329e+03,
       2.192e+03, 5.009e+03, 4.537e+03, 2.635e+03, 4.904e+03, 3.406e+03,
       1.009e+03, 1.838e+03, 2.454e+03, 2.889e+03, 

In [43]:
df["Delivery_Rating"].unique()

array([4.5, 4.2, 4.3, 4.4, nan, 3.9, 4.1, 4. , 4.6, 2.8, 3.7, 3.8, 3.4,
       3.6, 3.2, 3.3, 2.9, 3.5, 4.8, 3.1, 3. , 2.6, 2.5])

In [44]:
df["Delivery_Rating_Count"].unique()

array([  838.,   524., 22100., ...,  2029.,   878.,  4300.])

In [45]:
missing_values=['??','na','X','999999']
df=df.replace(missing_values,np.NaN)
df

Restaurant_Name                                           Category  \
0              Burma Burma  Asian, Burmese, Bubble Tea, Salad, Tea, Desser...   
1     Windmills Craftworks  Continental, Fast Food, Kebab, Beverages, Ital...   
2           CTR Shri Sagar                                       South Indian   
3     Brahmin's Coffee Bar                                       South Indian   
4         Milano Ice Cream                     Desserts, Ice Cream, Beverages   
...                    ...                                                ...   
5104     Chopstick Kitchen                            Chinese, Momos, Seafood   
5105         Punjabi Dhaba                                       North Indian   
5106  Abhiruchi Restaurant  Biryani, Andhra, North Indian, Chinese, Hydera...   
5107      The Q Restaurant                      North Indian, Chinese, Kerala   
5108      Flavors Of India           North Indian, Chinese, Andhra, Fast Food   

      Pricing_for_2                          Locality  Dining_Rating  \
0              1500            Indiranagar, Bangalore            4.9   
1              2500   Windmills Craftworks, Bangalore            4.9   
2               150           Malleshwaram, Bangalore            4.9   
3               100           Basavanagudi, Bangalore            4.9   
4               400            Indiranagar, Bangalore            4.9   
...             ...                               ...            ...   
5104            600         CV Raman Nagar, Bangalore            3.3   
5105            600                 Jakkur, Bangalore            3.3   
5106            550          Sarjapur Road, Bangalore            3.3   
5107            550               Nagawara, Bangalore            3.3   
5108            800           Marathahalli, Bangalore            3.3   

      Dining_Review_Count  Delivery_Rating  Delivery_Rating_Count  \
0                  2790.0              4.5                  838.0   
1                  6543.0              4.2                  524.0   
2                  4837.0              4.3                22100.0   
3                  2975.0              4.4                  372.0   
4                  2575.0              4.4                 1180.0   
...                   ...              ...                    ...   
5104                 79.0              3.1                  895.0   
5105                 21.0              3.9                  878.0   
5106                 36.0              3.8                 4300.0   
5107                 97.0              NaN                    0.0   
5108                 34.0              NaN                   11.0   

                                                Website  \
0     https://www.zomato.com/bangalore/burma-burma-i...   
1     https://www.zomato.com/bangalore/windmills-cra...   
2     https://www.zomato.com/bangalore/ctr-shri-saga...   
3     https://www.zomato.com/bangalore/brahmins-coff...   
4     https://www.zomato.com/bangalore/milano-ice-cr...   
...                                                 ...   
5104  https://www.zomato.com/bangalore/chopstick-kit...   
5105  https://www.zomato.com/bangalore/punjabi-dhaba...   
5106  https://www.zomato.com/bangalore/abhiruchi-res...   
5107  https://www.zomato.com/bangalore/the-q-restaur...   
5108  https://www.zomato.com/bangalore/flavors-of-in...   

                                                Address   Latitude  Longitude  
0     607, Ground Floor, 12th Main, Hal 2nd Stage, I...  12.970394  77.644713  
1     78, Immaine Epip Industrial Area, Whitefield B...  12.982413  77.721979  
2      7th Cross, Margosa Road, Malleshwaram, Bangalore  12.998270  77.569455  
3          Ranga Rao Road, Near Basavanagudi, Bangalore  12.954043  77.568865  
4     460, 2nd Cross, Krishna Temple Road, Indiranag...  12.979121  77.644039  
...                                                 ...        ...        ...  
5104  Shop 4, Kalpavruksha Complex, 13th Cross, Cauv...  12.977300  77.6656

In [46]:
df.dtypes

Restaurant_Name           object
Category                  object
Pricing_for_2              int64
Locality                  object
Dining_Rating            float64
Dining_Review_Count      float64
Delivery_Rating          float64
Delivery_Rating_Count    float64
Website                   object
Address                   object
Latitude                 float64
Longitude                float64
dtype: object

In [47]:
df["Dining_Rating"].isna=round(df["Dining_Rating"].mean(),2)
df["Delivery_Rating"].isna=round(df["Delivery_Rating"].mean(),2)
df

Restaurant_Name                                           Category  \
0              Burma Burma  Asian, Burmese, Bubble Tea, Salad, Tea, Desser...   
1     Windmills Craftworks  Continental, Fast Food, Kebab, Beverages, Ital...   
2           CTR Shri Sagar                                       South Indian   
3     Brahmin's Coffee Bar                                       South Indian   
4         Milano Ice Cream                     Desserts, Ice Cream, Beverages   
...                    ...                                                ...   
5104     Chopstick Kitchen                            Chinese, Momos, Seafood   
5105         Punjabi Dhaba                                       North Indian   
5106  Abhiruchi Restaurant  Biryani, Andhra, North Indian, Chinese, Hydera...   
5107      The Q Restaurant                      North Indian, Chinese, Kerala   
5108      Flavors Of India           North Indian, Chinese, Andhra, Fast Food   

      Pricing_for_2                          Locality  Dining_Rating  \
0              1500            Indiranagar, Bangalore            4.9   
1              2500   Windmills Craftworks, Bangalore            4.9   
2               150           Malleshwaram, Bangalore            4.9   
3               100           Basavanagudi, Bangalore            4.9   
4               400            Indiranagar, Bangalore            4.9   
...             ...                               ...            ...   
5104            600         CV Raman Nagar, Bangalore            3.3   
5105            600                 Jakkur, Bangalore            3.3   
5106            550          Sarjapur Road, Bangalore            3.3   
5107            550               Nagawara, Bangalore            3.3   
5108            800           Marathahalli, Bangalore            3.3   

      Dining_Review_Count  Delivery_Rating  Delivery_Rating_Count  \
0                  2790.0              4.5                  838.0   
1                  6543.0              4.2                  524.0   
2                  4837.0              4.3                22100.0   
3                  2975.0              4.4                  372.0   
4                  2575.0              4.4                 1180.0   
...                   ...              ...                    ...   
5104                 79.0              3.1                  895.0   
5105                 21.0              3.9                  878.0   
5106                 36.0              3.8                 4300.0   
5107                 97.0              NaN                    0.0   
5108                 34.0              NaN                   11.0   

                                                Website  \
0     https://www.zomato.com/bangalore/burma-burma-i...   
1     https://www.zomato.com/bangalore/windmills-cra...   
2     https://www.zomato.com/bangalore/ctr-shri-saga...   
3     https://www.zomato.com/bangalore/brahmins-coff...   
4     https://www.zomato.com/bangalore/milano-ice-cr...   
...                                                 ...   
5104  https://www.zomato.com/bangalore/chopstick-kit...   
5105  https://www.zomato.com/bangalore/punjabi-dhaba...   
5106  https://www.zomato.com/bangalore/abhiruchi-res...   
5107  https://www.zomato.com/bangalore/the-q-restaur...   
5108  https://www.zomato.com/bangalore/flavors-of-in...   

                                                Address   Latitude  Longitude  
0     607, Ground Floor, 12th Main, Hal 2nd Stage, I...  12.970394  77.644713  
1     78, Immaine Epip Industrial Area, Whitefield B...  12.982413  77.721979  
2      7th Cross, Margosa Road, Malleshwaram, Bangalore  12.998270  77.569455  
3          Ranga Rao Road, Near Basavanagudi, Bangalore  12.954043  77.568865  
4     460, 2nd Cross, Krishna Temple Road, Indiranag...  12.979121  77.644039  
...                                                 ...        ...        ...  
5104  Shop 4, Kalpavruksha Complex, 13th Cross, Cauv...  12.977300  77.6656